Sprint 2
Kocherg1n/middle.messenger.praktikum.yandex pull request #2
Opened 2022-08-10 13:05 UTC by Kocherg1n

2022-08-10 15:13 UTC, podlovchenko requested changes
Привет, в целом все хорошо) Есть несколько замечаний:
1. Нет ссылки на фигму в ридми
2. На нетлифай старая версия
3. Нет страницы для отображения ошибок

Здорово, что использовал алиасы и класс Component дженериком👍

2022-08-10 15:13 UTC, podlovchenko commented on package.json
> +    "@types/uuid": "^8.3.4",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-08-10 15:13 UTC, podlovchenko commented on src/components/form/index.ts
> +  _isValid: boolean = false
Для приватных полей не хватает модификатора private

2022-08-10 15:13 UTC, podlovchenko commented on src/core/api.ts
> +enum METHODS {
enum обычно называют в формате CamelCase

2022-08-10 15:13 UTC, podlovchenko commented on src/core/api.ts
> +  method?: keyof typeof METHODS
```suggestion
  method?: METHODS
```

2022-08-10 15:13 UTC, podlovchenko commented on src/core/api.ts
> +  put = this.sendMethod.bind(this, 'PUT')
Можно использовать здесь enum

2022-08-10 15:13 UTC, podlovchenko commented on src/index.ts
> +
Лишние строки

2022-08-10 17:10 UTC, Kocherg1n commented on package.json
> +    "@types/uuid": "^8.3.4",
\+

2022-08-10 17:10 UTC, Kocherg1n commented on src/components/form/index.ts
> +  _isValid: boolean = false
\+

2022-08-10 17:10 UTC, Kocherg1n commented on src/core/api.ts
> +enum METHODS {
\+

2022-08-10 17:10 UTC, Kocherg1n commented on src/core/api.ts
> +  method?: keyof typeof METHODS
\+

2022-08-10 17:10 UTC, Kocherg1n commented on src/core/api.ts
> +  put = this.sendMethod.bind(this, 'PUT')
\+

2022-08-10 17:10 UTC, Kocherg1n commented on src/index.ts
> +
\+

2022-08-10 17:10 UTC, Kocherg1n commented on src/index.ts
> +    break
\+

2022-08-10 17:10 UTC, Kocherg1n commented on src/index.ts
> +
\+

2022-08-10 17:10 UTC, Kocherg1n commented on src/utils/validation.ts
> +    error: 'Пароль должен содержать минимум одну заглавную букву, цифру и иметь не менее 8 символов',
\+

2022-08-11 08:55 UTC, podlovchenko commented
Привет, все еще нет ссылки на фигму, на нетлифае page not found, если перейти на страницу регистрации
Можно добавить файл netlify.tom с [[redirects]]

2022-08-11 10:02 UTC, Kocherg1n commented
> 

сори не проверил сразу что все страницы открываются,
ссылки на фигму нет макеты в директории проекта в папке ui (так приняли на первом спринте)

2022-08-11 10:32 UTC, podlovchenko commented
Гуд, работу принимаю 👍

2022-08-11 11:03 UTC, merged